'useClient';
import MainStyles from '../../../styles/style-main.css';
import HomeStyles from '../../../styles/home-styles.css';
import MediaStyles from '../../../styles/media-styles.css';
export {MainStyles, HomeStyles, MediaStyles};

import NavBar from '../NavBar.jsx';
import ProjectsContainer from '../Projects.jsx';

export const metadata = {
  title: 'Archivo Imperial',
  description: 'Generated by Next.js',
}

export default function HomePageLayout() {
    return (<>
        <NavBar/>
        <ProjectsContainer/>
    </>
    );
}
    