'useClient';
import MainStyles from '../../../styles/style-main.css';
import HomeStyles from '../../../styles/home-styles.css';
import MediaStyles from '../../../styles/media-styles.css';

export const metadata = {
  title: 'Archivo Imperial',
  description: 'Generated by Next.js',
}

export default function LogPageLayout({children}) {
    return(<div className="login"> 
        <TitleLogo/>
            {children}
        <WelcomeBanner/>
    </div>
    )
}

function WelcomeContainer() {

}

function TitleLogo() {
    return (
    <div className="logo">
			<a href="/">
                <img src="./img/icons/research.png" alt="Imperial logo" height="50"/>
            </a>	
			<h3>Registro de nuevo usuario</h3>
    </div>);
}

function WelcomeBanner() {
    return(<div className="welcome-banner">
        <img src="img/tower.gif" alt="Base de Archivos de Scariff" height="600"/>
    </div>);
}
