'useClient';


export const metadata = {
  title: 'Archivo Imperial',
  description: 'Generated by Next.js',
}

function TopBar({title}) { 
    return <header>
        Hola mama
    </header>;
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
    <head>
        <meta charSet="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body><TopBar/>{children}</body>
    </html>
  );
}
