'using client';
import HomePageLayout from "../components/layouts/HomePageLayout";
import {useState} from 'react';

export const [isLogged, setLogged] = useState( 
    JSON.parse(window.localStorage.getItem("userInfo") || false
));

export const metadata = {
  title: 'Archivo Imperial',
  description: 'Generated by Next.js',
}

export default function LandingPage() {
    if(isLogged) {
        return(<HomePageLayout/>);
    }
    else {
        navigate("/login");
    }
}