'useClient';
import MainStyles from  '../styles/style-main.css';
import HomeStyles from '../styles/home-styles.css';
import MediaStyles from '../styles/media-styles.css';

export const metadata = {
  title: 'Archivo Imperial',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
    <head>
        <meta charSet="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
      {children}
    </body>
    </html>
  );
}
